const actions = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCEED: 'FETCH_PRODUCTS_SUCCEED',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',

  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_FROM_CART: 'CLEAR_FROM_CART',

  APPLY_PROMO_CODE_REQUEST: 'APPLY_PROMO_CODE_REQUEST',
  APPLY_PROMO_CODE_SUCCEED: 'APPLY_PROMO_CODE_SUCCEED',

  CHECKOUT_CART_REQUEST: 'CHECKOUT_CART_REQUEST',
  CHECKOUT_CART_SUCCEED: 'CHECKOUT_CART_SUCCEED',

  CHECKOUT_CART_RESET: 'CHECKOUT_CART_RESET'
}

export default actions
