const actions = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCEED: 'FETCH_PRODUCTS_SUCCEED',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',

  SELECT_PRODUCTS: 'SELECT_PRODUCTS',

  APPLY_PROMO_CODE_REQUEST: 'APPLY_PROMO_CODE_REQUEST',
  APPLY_PROMO_CODE_SUCCEED: 'APPLY_PROMO_CODE_SUCCEED',

  CHECKOUT_PRODUCTS_REQUEST: 'CHECKOUT_PRODUCTS',
  CHECKOUT_PRODUCTS_SUCCEED: 'CHECKOUT_PRODUCTS_SUCCEED',

  CHECKOUT_PRODUCTS_RESET: 'CHECKOUT_PRODUCTS_RESET'
}

export const selectProductsTypes = {
  INC: 'INC',
  DEC: 'DEC',
  REMOVE: 'REMOVE'
}

export default actions
