const actionTypes = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCEED: 'FETCH_PRODUCTS_SUCCEED',
  FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',

  PRODUCTS_SELECTED: 'PRODUCTS_SELECTED',

  CHECK_PROMO_CODE: 'CHECK_PROMO_CODE',
  CHECK_PROMO_CODE_SUCCEED: 'CHECK_PROMO_CODE_SUCCEED',

  CHECKOUT_PRODUCTS: 'CHECKOUT_PRODUCTS',
  CHECKOUT_PRODUCTS_SUCCEED: 'CHECKOUT_PRODUCTS_SUCCEED'
}

export const selectProductsTypes = {
  INC: 'INC',
  DEC: 'DEC',
  REMOVE: 'REMOVE'
}

export default actionTypes
